[package]
name = "proxy_engine"
version = "0.1.0"
edition = "2021"

[dependencies]
core_crypto   = { path = "../core_crypto" }
tokio         = { version = "1", features = ["full"] }
tokio-util    = { version = "0.7", features = ["codec"] }
bytes         = "1"
thiserror     = "1"
hkdf          = "0.12"
sha2          = "0.10"
aes-gcm       = { version = "0.10", features = ["zeroize"] }
zeroize       = { version = "1", features = ["zeroize_derive"] }
tracing       = "0.1"
rand          = "0.8"
blake3 = "1.8.7"

[dev-dependencies]
tokio              = { version = "1", features = ["full", "test-util"] }
tracing-subscriber = "0.3"
futures-util       = { version = "0.3", features = ["sink"] }
