//! Credential storage and verification.
//!
//! Passwords are stored as Argon2id PHC strings using the RustCrypto `argon2`
//! crate. The PHC format (`$argon2id$v=19$m=65536,t=3,p=4$...`) is self-describing
//! and supports parameter migration without schema changes.
//!
//! ## Security properties
//!
//! - Memory-hard (m=65536 KiB): resists GPU/ASIC brute-force
//! - Three iterations (t=3): OWASP recommended minimum
//! - Four parallel lanes (p=4): matches typical server core count
//! - 32-byte random salt per credential (generated by `OsRng`)
//! - 32-byte output hash
//! - Constant-time verification via argon2 crate's own comparison
//! - Sentinel hash used when username is not found (prevents timing oracle)

use argon2::{
    password_hash::{rand_core::OsRng, PasswordHash, PasswordHasher, PasswordVerifier, SaltString},
    Argon2, Params, Version,
};

// Argon2id parameters — OWASP recommended minimums (2024)
const ARGON2_M_COST: u32 = 65_536; // 64 MiB memory
const ARGON2_T_COST: u32 = 3; // 3 iterations
const ARGON2_P_COST: u32 = 4; // 4 parallel lanes
const ARGON2_OUTPUT: usize = 32; // 32-byte output

/// Build the Argon2id instance with our fixed parameters.
fn argon2() -> Argon2<'static> {
    let params = Params::new(
        ARGON2_M_COST,
        ARGON2_T_COST,
        ARGON2_P_COST,
        Some(ARGON2_OUTPUT),
    )
    .expect("Argon2 params are statically valid");
    Argon2::new(argon2::Algorithm::Argon2id, Version::V0x13, params)
}

/// Hash a password and return the PHC string for storage.
///
/// Uses `OsRng` for the salt — never call this with a user-supplied salt.
///
/// # Errors
/// Returns an error string on hash failure (should never happen in practice
/// with valid parameters, but must not panic in production).
pub fn hash_password(password: &str) -> Result<String, String> {
    let salt = SaltString::generate(&mut OsRng);
    argon2()
        .hash_password(password.as_bytes(), &salt)
        .map(|h| h.to_string())
        .map_err(|e| format!("Argon2 hash failed: {e}"))
}

/// Verify a password against a stored PHC hash.
///
/// Always takes approximately the same time regardless of whether the password
/// is correct, due to argon2's constant-time comparison.
///
/// Returns `true` if the password matches, `false` otherwise.
/// Never panics — errors are treated as verification failures.
pub fn verify_password(password: &str, phc_hash: &str) -> bool {
    let parsed = match PasswordHash::new(phc_hash) {
        Ok(h) => h,
        Err(e) => {
            tracing::error!("Failed to parse stored PHC hash: {e}");
            return false;
        }
    };
    argon2()
        .verify_password(password.as_bytes(), &parsed)
        .is_ok()
}

/// A sentinel PHC hash used when a username is not found in the store.
///
/// Verifying against this sentinel will always fail, but it ensures the
/// Argon2 computation always runs — preventing a timing oracle that would
/// allow an attacker to enumerate valid usernames.
static SENTINEL_HASH: std::sync::OnceLock<String> = std::sync::OnceLock::new();

pub fn sentinel_hash() -> &'static str {
    SENTINEL_HASH.get_or_init(|| {
        use argon2::password_hash::rand_core::RngCore;
        let mut random_bytes = [0u8; 64];
        OsRng.fill_bytes(&mut random_bytes);
        // Hash a completely random secret — result is discarded but computation runs
        hash_password(&hex::encode(random_bytes)).expect("sentinel hash must succeed")
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_hash_and_verify_roundtrip() {
        let pw = "correct_horse_battery_staple";
        let phc = hash_password(pw).expect("hash should succeed");
        assert!(verify_password(pw, &phc), "correct password must verify");
    }

    #[test]
    fn test_wrong_password_rejected() {
        let phc = hash_password("right_password").expect("hash should succeed");
        assert!(!verify_password("wrong_password", &phc));
    }

    #[test]
    fn test_empty_password_rejected() {
        let phc = hash_password("real_password").expect("hash should succeed");
        assert!(!verify_password("", &phc));
    }

    #[test]
    fn test_sentinel_always_fails() {
        // Sentinel hash must never accidentally verify a real password
        assert!(!verify_password("any_password", sentinel_hash()));
        assert!(!verify_password(
            "__sentinel_vardhan_quantum_placeholder__",
            sentinel_hash()
        ));
    }

    #[test]
    fn test_different_salts_produce_different_hashes() {
        let pw = "same_password";
        let h1 = hash_password(pw).unwrap();
        let h2 = hash_password(pw).unwrap();
        // Two hashes of the same password must differ (different random salts)
        assert_ne!(h1, h2, "salts must differ between hashes");
        // But both must verify correctly
        assert!(verify_password(pw, &h1));
        assert!(verify_password(pw, &h2));
    }
}
